spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true


server:
  context-path: /sell
  port: 8090
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: /Users/Iverson/log/tomcat/sell.log
#  level:
#    root: info
#    com.cell.LoggerTest: debug
#
#
#
